version: '3.8'

services:
  price-generator:
    build: .
    container_name: price-ts-generator
    environment:
      - NODE_ENV=production
      - API_BASE_URL=${API_BASE_URL}
      - API_PATH=${API_PATH}
    volumes:
      # 挂载输出目录到宿主机
      - ./output:/app/output
      # 挂载环境变量文件
      - ./.env:/app/.env:ro
      # 如果需要挂载用户数据文件
      - ./sample-card-data.json:/app/sample-card-data.json:ro
    working_dir: /app
    
    # 运行命令示例
    # 生成单个用户图表
    # command: ["ts-node", "scripts/chart-generator.ts", "single", "username"]
    
    # 批量生成图表
    # command: ["ts-node", "scripts/chart-generator.ts", "batch", "sample-card-data.json"]
    
    # 生成单个用户卡片
    # command: ["ts-node", "scripts/linkol-card-generator.ts", "single", "username"]
    
    # 批量生成卡片
    # command: ["ts-node", "scripts/linkol-card-generator.ts", "batch", "sample-card-data.json"]
    
    # 默认显示帮助信息
    command: ["ts-node", "scripts/chart-generator.ts", "--help"]
    
    # 如果需要交互式运行，可以取消注释下面的行
    # stdin_open: true
    # tty: true
    
    restart: unless-stopped
